### ISSUE TITLE
Textures in Godot to visionOS transition - not consistent

### ISSUE THREAD

**Issue by dpentecost** [kevinw/GodotVisionExample#1]
Textured objects are displayed one way in Godot editor and when played, another in the visionOS simulator through Xcode. 
<img width="612" alt="Screenshot 2024-02-07 at 10 03 21 AM" src="https://github.com/kevinw/GodotVisionExample/assets/71628/423e9dc0-9195-4661-abe8-5b70704c5634">
<img width="754" alt="Screenshot 2024-02-07 at 10 03 00 AM" src="https://github.com/kevinw/GodotVisionExample/assets/71628/a249dc03-ac5d-4748-aa88-5cac46d844ee">

**Comment by adamwatters** [comment]
@dpentecost fixed! if you don't want to re-clone GodotVisionExample, you should be able to update only the GodotVision dependency in Xcode. GodotVisionExample (in the project navigator left bar) > GodotVisionExample (under Project) > Package Dependencies... set `Dependency Rule` to `Commit` and paste in the SHA for the update: 22b17c5026b4226df0f3fd24d062de2ea1097a0d

**Comment by dpentecost** [comment]
Amazing!

I suspect I’ll get very good at updating at the rate you add new stuff

@dpentecost
Cell 646 704 2021
