### ISSUE TITLE
Lighting in Godot Project does not carry into visionOS

### ISSUE THREAD

**Issue by dpentecost** [kevinw/GodotVisionExample#2]
Objects that look well-lit in Godot are very dull, dark in visionOS. Changes to lighting intensity make no difference in visionOS

**Comment by adamwatters** [comment]
In the simulator, or on the device? There's a bug in the simulator where you have to change the lighting environment once for it to take effect.

If on the device... I'm not sure! You can't add lights to scenes in RealityKit, it uses whatever light is in your environment. There is an emissive property on RK materials, so maybe that could work.

**Comment by kevinw** [comment]
@adamwatters "You can't add lights to scenes in RealityKit" I'm not 100% sure this is true, I do remember seeing [ImageBasedLightComponent](https://developer.apple.com/documentation/realitykit/imagebasedlightcomponent) being used in [Hello World](https://developer.apple.com/documentation/visionos/world), but yeah not familiar with the way these work yet!

**Comment by dpentecost** [comment]
So you are right about the bug - changing scene and then back makes it pick up the room lighting. But I have added a sphere with an earth texture and nothing I do improves the lighting on it. Tried emission - works in Godot but makes no difference in visionOS. I guess I will look at the plain shaders you used and see if I can improve it.
<img width="556" alt="Screenshot 2024-02-12 at 11 27 38 AM" src="https://github.com/kevinw/GodotVisionExample/assets/71628/51eb2c01-8275-4bd1-9686-07986edba1ac">
<img width="509" alt="Screenshot 2024-02-12 at 11 26 58 AM" src="https://github.com/kevinw/GodotVisionExample/assets/71628/e210fe26-c79e-4c15-b7ca-73a31af9db57">

**Comment by adamwatters** [comment]
@dpentecost - sorry for the delay - can you send the globe texture you're trying to use as an attachment here? I'll poke around and see if I can get a solution for you!

**Comment by dpentecost** [comment]
Will do a little later today. Thanks.

**Comment by dpentecost** [comment]
I first used a 4KX4K texture but it was too large to upload here. I just tried this 2KX2K texture with the same result. Emission has no effect. Good luck!


![M_earth_baseColor2K2K](https://github.com/kevinw/GodotVisionExample/assets/71628/92e1f1ba-b41c-4d3e-a2ea-0c74cac6c9b2)

**Comment by kevinw** [comment]
@dpentecost I just bumped the GodotVision commit to include a fix for emission textures. Let me know if it works for you!

https://github.com/kevinw/GodotVisionExample/commit/4a41bf71c2f58f4c0d48dd70a0fc33b034e3d6a5

**Comment by dpentecost** [comment]
Yes, it works, thanks. I'll be working through some other things, will let you know.
