### ISSUE TITLE
Hello Example - drag block doesn't push the guy

### ISSUE THREAD

**Issue by adamwatters** [kevinw/GodotVisionExample#4]
We broke the physics in the initial example when we switched the physics engine to Jolt.

Try using `AnimatableBody3D` instead of `StaticBody3d`.

**Comment by kevinw** [comment]
I glanced at the scene--I think there's one more step. I think if all the objects involved had Collision Layer 1 and Mask 1, things would work too. Not sure how they got set otherwise!

**Comment by adamwatters** [comment]
merging this for now because it works, but let's take another look at the example to make sure its a good reference for the best way!

https://github.com/kevinw/GodotVisionExample/pull/5/commits/443506ee21d0702035ad1bf44398992669a094c3
